Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -15,18 +15,26 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          clean: true
+
+      - name: Ensure Dockerfile is present
+        run: |
+          echo "Contenido del repo:"
+          ls -R .
+          if [ ! -f "./Dockerfile" ]; then
+            echo "ERROR: Dockerfile no encontrado"
+            exit 1
+          fi
 
       - name: Login to Docker Hub
         run: |
           echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
 
-      - name: Enable Docker Buildx
-        run: |
-          docker buildx create --use
-
       - name: Build Docker image
         run: |
-          docker buildx build --load -t $IMAGE_NAME:$TAG .
+          docker build -t $IMAGE_NAME:$TAG .
 
       - name: Push Docker image
         run: |
@@ -44,18 +52,3 @@ jobs:
       - name: Wait for rollout
         run: |
           kubectl rollout status deployment/kubefoods-backend --timeout=30s
-
-      - name: Validate service health
-        id: validate
-        run: |
-          URL="${{ secrets.SERVICE_URL }}"
-          STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL)
-          echo "STATUS=$STATUS"
-          if [ "$STATUS" -ne 200 ]; then
-            exit 1
-          fi
-
-      - name: Rollback Deployment
-        if: failure() && steps.validate.outcome == 'failure'
-        run: |
-          kubectl rollout undo deployment/kubefoods-backend
